

/* SELECT 
NAMESURNAME, GENDER, DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,BIRTHDATE,

CASE WHEN GENDER = 'E' THEN 'Sn ' +
'Sn ' + NAMESURNAME + ' ' + CONVERT(VARCHAR,DATEDIFF(YEAR,BIRTHDATE,GETDATE())) + '. yaþýnýzý kutlar, aileniz ile birlikte saðlýklý,mutlu ve huzurlu yýllar dileriz.'

FROM USERS
WHERE
DATEPART(MONTH,BIRTHDATE) = DATEPART(MONTH,GETDATE())
AND DATEPART(DAY,BIRTHDATE) = DATEPART(DAY,GETDATE()) */


CREATE VIEW VWBUGUNDOGANLARSS
AS
SELECT 
NAMESURNAME ADSOYAD,
'Sn ' + NAMESURNAME + ' ' + GENDEREXP + '; ' + CONVERT(varchar,AGE) + '. yeni yaþýnýz kutlu olsun.'
FROM
(
	SELECT NAMESURNAME,GENDER,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE, BIRTHDATE,
	IIF(GENDER = 'K','Haným','Bey') GENDEREXP
	FROM USERS
	WHERE
	DATEPART(MONTH,BIRTHDATE) = DATEPART(MONTH,GETDATE())
	AND DATEPART(DAY,BIRTHDATE) = DATEPART(MONTH,GETDATE())
) T