

SELECT * FROM ORDERS  WHERE ID = 1
SELECT * FROM ORDERDETAILS WHERE ORDERID = 1




SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ORDERID = 1 


CREATE VIEW VWMONTHLYSALES
AS
  
SELECT DATEPART(MONTH,DATE_) MONTHNR,DATENAME(MONTH,DATE_) MONTH_,SUM(TOTALPRICE) TOTALSALES
FROM ORDERS 

GROUP BY DATENAME(MONTH,DATE_),DATEPART(MONTH,DATE_)
ORDER BY 1

--VIEW'DE OLUSTURURKEN ORDER BY Kullanýlarak VIEW olusturulamaz.


SET LANGUAGE Turkish
SELECT * FROM VWMONTHLYSALES 
ORDER BY 1


