

CREATE VIEW WVINVOICEDURATION 
AS
SELECT 
C.CITY  SEHIR,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) DURATION

FROM ORDERS O
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN ADDRESS A ON A.ID = I.ADDRESSID
JOIN CITIES C ON C.ID = A.ID

GROUP BY C.CITY


SELECT * FROM WVINVOICEDURATION ORDER BY DURATION ASC