
CREATE FUNCTION DBO.ITEMINFO(@ITEMID INT)
RETURNS TABLE 
AS
RETURN 
(
	SELECT I.ID,I.ITEMCODE,I.ITEMNAME,SUM(OD.AMOUNT) TOTALAMOUNT,
	SUM(OD.LINETOTAL) TOTALSALE, MIN(OD.UNITPRICE) MINPRICE, MAX(OD.UNITPRICE) MAXPRICE,
	AVG(OD.UNITPRICE) AVGPRICE FROM ITEMS I
	JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
	WHERE I.ID = @ITEMID
	GROUP BY I.ID,I.ITEMCODE,I.ITEMNAME
)
GO
