
--MULTÝ STATEMENT FUNCITONS ORNEKLERI 


CREATE FUNCTION DBO.ITEMINFO22 (
	@ITEMID INT
)

RETURNS 
@RESULT TABLE 
(
ID INT,ITEMCODE VARCHAR(50), ITEMNAME VARCHAR(100),TOTALAMOUNT INT, TOTALSALE FLOAT,
MINPRICE FLOAT, MAXPRICE FLOAT, AVGPRICE FLOAT
)
AS
BEGIN
	
	INSERT INTO @RESULT(ID,ITEMCODE,ITEMNAME,TOTALAMOUNT,TOTALSALE,MINPRICE,MAXPRICE,AVGPRICE)
	SELECT I.ID, I.ITEMCODE,I.ITEMNAME, SUM (OD.AMOUNT) AS TOTALAMOUNT, SUM(OD.LINETOTAL) AS TOTALSALE,
	MIN(OD.UNITPRICE) MINFIYAT, MAX(OD.UNITPRICE) MAXPRICE, AVG(OD.UNITPRICE) AVGPRICE
	FROM ITEMS I
	JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
	WHERE I.ID = @ITEMID
	GROUP BY I.ID, I.ITEMCODE, I.ITEMNAME
	

RETURN 
END
GO


--SCALAR Deðerler = Toplam Satýþ miktarýný getirenler yani CREATE,UPDATE,DELETE Kullanabiliriz.

--TABLE Valued = SELECT atabiliriz sadece. 


--INLINE Fonksiyonlarda INSERT,UPDATE,DELETE iþlemlerini gerçekleþtiremeyiz.

--MULTI STATEMENT Fonksiyonlarda CREATE,UPDATE,DELETE iþlemleri gerçekleþir. 



SELECT * FROM ITEMS