

--Her bir futbolcunun:
-- mevcut oynadýðý takýmý
-- kaç farklý takýmda oynadýðý
-- kaç yýldýr futbol oynadýðýný
-- getiren fonksiyonlarý yazalým. 


SELECT PLAYER_API_ID, PLAYER_NAME
FROM LAB_PLAYER WHERE PLAYER_NAME LIKE '%messi%'
SELECT * FROM LAB_MATCH_PLAYER
WHERE PLAYERID = 30981


SELECT TOP 1 *  FROM LAB_MATCH_PLAYER WHERE PLAYERID = 30983


CREATE FUNCTION DBO.GETCURRENTTEAM(@PLAYERID AS INT)
RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @RESULT AS VARCHAR(100)
SELECT TOP 1 @RESULT = TEAM
FROM LAB_MATCH_PLAYER
WHERE PLAYERID = @PLAYERID
ORDER BY DATE_ DESC

RETURN @RESULT
END






CREATE FUNCTION DBO.GETCOUNTTEAM (@PLAYERID AS INTEGER)
RETURNS INT
AS
BEGIN
DECLARE @RESULT AS INT
SELECT @RESULT = COUNT(DISTINCT TEAM) FROM LAB_MATCH_PLAYER
WHERE PLAYERID = @PLAYERID
RETURN @RESULT

END



CREATE FUNCTION DBO.GETMATCHCOUNT (@PLAYERID AS INTEGER)
RETURNS INT
AS
BEGIN
DECLARE @RESULT AS INT
SELECT @RESULT = COUNT(*) FROM LAB_MATCH_PLAYER
WHERE PLAYERID = @PLAYERID
RETURN @RESULT
END


CREATE FUNCTION DBO.GETPLAYINGYEAR (@PLAYERID AS INTEGER)
RETURNS INT 
AS 
BEGIN
DECLARE @RESULT AS INT
SELECT @RESULT = DATEDIFF(YEAR,MIN(DATE_),MAX(DATE_)) FROM LAB_MATCH_PLAYER
WHERE PLAYERID = @PLAYERID
RETURN @RESULT
END