DECLARE @FICHENO AS VARCHAR(20)
DECLARE @DATE_ AS DATETIME
DECLARE @ITEMCODE AS VARCHAR(20)
DECLARE @ITEMNAME AS VARCHAR(100)
DECLARE @BRAND AS VARCHAR(100)
DECLARE @CATEGORY1 AS VARCHAR(100)
DECLARE @CATEGORY2 AS VARCHAR(100)
DECLARE @CATEGORY3 AS VARCHAR(100)
DECLARE @CATEGORY4 AS VARCHAR(100)
DECLARE @AMOUNT AS INT
DECLARE @PRICE AS FLOAT 
DECLARE @TOTALPRICE AS FLOAT
DECLARE @CUSTOMERCODE AS VARCHAR(100)
DECLARE @CUSTOMERNAME AS VARCHAR(100) 
DECLARE @CUSTOMERBIRHTDATE DATE
DECLARE @CUSTOMERGENDER AS CHAR(1)
DECLARE @BRANCH VARCHAR(100)
DECLARE @CITY AS VARCHAR(100) 
DECLARE @DISTRICT AS VARCHAR(100)
DECLARE @REGION AS VARCHAR(100)
DECLARE @RANDID AS INT


SELECT @FICHENO = CONVERT(varchar, CONVERT(INT,MAX(FICHENO)) + 1) FROM LAB05_SALES
SET @FICHENO = REPLICATE('0', 10 - LEN(@FICHENO)) + @FICHENO

SET @RANDID = 365 * RAND()
SET @DATE_ = DATEADD(DAY,@RANDID,'2021-01-01')
SET @DATE_ = DATEADD(HOUR,8,@DATE_)
SET @RANDID = 14*60*60
SET @DATE_ = DATEADD(SECOND,@RANDID,@DATE_)
SET @RANDID () = 1 + RAND() * 28067

SELECT @ITEMCODE = ITEMCODE, @ITEMNAME = ITEMNAME, @BRAND = BRAND, @CATEGORY1 = CATEGORY1, @CATEGORY2 = @CATEGORY2,
@CATEGORY3 = CATEGORY3, @CATEGORY4 = @CATEGORY4, @PRICE = SALEPRICE FROM LAB05_ITEMS WHERE ID = @RANDID

SET @AMOUNT = 1 + (RAND() * 9 )

SET @PRICE = (@PRICE*0.75)*(1+RAND()*0.5)
SET @TOTALPRICE = @AMOUNT * @PRICE 

SELECT @FICHENO,@DATE_,@ITEMCODE,@ITEMNAME,@BRAND,@CATEGORY1,@CATEGORY2,@CATEGORY3,@CATEGORY4,@AMOUNT,@PRICE,@TOTALPRICE

SET @RANDID = RAND() * 81
SELECT @CITY = CITYNAME, @REGION = REGION FROM LAB05_CITIES WHERE @RANDID BETWEEN RANDOMBEG AND RANDOMEND


SELECT TOP 1 
@CUSTOMERCODE = ID, @CUSTOMERNAME = NAMESURNAME, @CUSTOMERBIRHTDATE = BIRTHDATE, @CUSTOMERGENDER = GENDER,
@DISTRICT = TOWN
FROM LAB05_CUSTOMERS WHERE CITY = @CITY ORDER BY NEWID()

SET @BRANCH = @CITY


INSERT INTO LAB05_SALES (FICHENO, DATE_, ITEMCODE, ITEMNAME, BRAND, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, AMOUNT, 
PRICE, TOTALPRICE, CUSTOMERCODE, CUSTOMERNAME, CUSTOMERBIRHTDATE, CUSTOMERGENDER, BRANCH, CITY, DISTRICT, REGION)
VALUES
(@FICHENO, @DATE_, @ITEMCODE, @ITEMNAME, @BRAND, @CATEGORY1, @CATEGORY2, @CATEGORY3, @CATEGORY4, @AMOUNT, @PRICE, @TOTALPRICE, 
@CUSTOMERCODE, @CUSTOMERNAME, @CUSTOMERBIRHTDATE, @CUSTOMERGENDER, @BRANCH, @CITY, @DISTRICT, @REGION)