

--Elimizde bir araç plaka veriseti var. Bir plakanýn tanýma noktasýndan geçen araçlarý kayýt altýna almak istiyoruz.
--Bu noktadan 24 saat içinde geçen araçlarý simule edecek T-SQL scriptini yazalým.


SELECT * FROM LAB04_CARMODELS
SELECT * FROM LAB04_PLATES
SELECT * FROM LAB04_PTSLOG
SELECT * FROM LAB04_PTSPOINT

INSERT INTO LAB04_PTSLOG (PTSPOINTID,PLATE,DATE_)
VALUES (1,'06BV3918','2022-08-27 13:04:22')

DECLARE @I AS INT = 0

WHILE @I<100000
BEGIN


	DECLARE @PLATE AS VARCHAR(20)
	DECLARE @PTSPOINTID AS INT = 1
	DECLARE @DATE AS DATETIME = '2022-08-27 00:00:00'
	DECLARE @RANDID AS INT
	DECLARE @RANDTIME AS INT
	SET @RANDID = 1 + RAND()*999999
	SELECT @PLATE = PLATE FROM LAB04_PLATES WHERE ID = @RANDID

	SET @RANDID = RAND()*24*60*60
	SET @DATE = DATEADD(SECOND,@RANDID,@DATE)
	SET @RANDTIME = RAND()*1000
	SET @DATE = DATEADD(MS,@RANDTIME,@DATE)

	SET @I = @I + 1

	INSERT INTO LAB04_PTSLOG (PTSPOINTID,PLATE,DATE_)
	VALUES (@PTSPOINTID,@PLATE,@DATE)
SELECT @PLATE,@RANDTIME,@DATE


END