

SELECT 
P.PTSNAME,L.DATE_,L.PLATE,CM.TITLE FROM LAB04_PTSLOG L
JOIN LAB04_PTSPOINT P ON P.ID = L.PTSPOINTID
JOIN LAB04_PLATES PL ON PL.PLATE = L.PLATE
JOIN LAB04_CARMODELS CM ON CM.ID = PL.CARID
ORDER BY L.DATE_


SELECT 
DATEPART(HOUR,L.DATE_) HOUR_,COUNT(L.ID) VEHICLECONTROL FROM LAB04_PTSLOG L
JOIN LAB04_PTSPOINT P ON P.ID = L.PTSPOINTID
JOIN LAB04_PLATES PL ON PL.PLATE = L.PLATE
JOIN LAB04_CARMODELS CM ON CM.ID = PL.CARID
GROUP BY DATEPART(HOUR,L.DATE_)
ORDER BY L.DATE_

SELECT 
DATEPART(HOUR,L.DATE_) HOUR_,COUNT(L.ID) VEHICLECONTROL
FROM LAB04_PTSLOG L
JOIN LAB04_PTSPOINT P ON P.ID = L.PTSPOINTID
JOIN LAB04_PLATES PL ON PL.PLATE = L.PLATE
JOIN LAB04_CARMODELS CM ON CM.ID = PL.CARID
GROUP  BY DATEPART(HOUR,L.DATE_)
ORDER BY 1