

--Bir termometrenin üzerinden gün içerisinde 30 saniyede bir ölçüm yapan bir sistem oluþturalým. Bu sistemde 30 saniyede bir termometrelerden rastgele
--deðer okuyup, bu deðerleri loglayacak bir mekanizma kuracak þekilde T-SQL Yazalým.


SELECT * FROM LAB02_DEVICES
SELECT * FROM LAB02_LOG

TRUNCATE TABLE LAB02_LOG

DECLARE @DEVICEID AS INT =1
DECLARE @DATE AS DATETIME = '2022-08-027 07:30:00'

WHILE @DATE <= '2022-08-027 17:30:00'
BEGIN
DECLARE @CURRENTVALUE AS FLOAT
 SELECT @CURRENTVALUE = CURRENTVALUE FROM LAB02_DEVICES WHERE ID = @DEVICEID
 IF @CURRENTVALUE = 0
 BEGIN
  SET @CURRENTVALUE = 18
  END
  DECLARE @NEWVALUE AS FLOAT
  SET @NEWVALUE = ROUND(@CURRENTVALUE -0.5 + RAND(),2)
  UPDATE LAB02_DEVICES SET CURRENTVALUE = @NEWVALUE WHERE ID = @DEVICEID
  INSERT INTO LAB02_LOG (DEVICEID,DATE_,VALUE_) VALUES (@DEVICEID,@DATE,@NEWVALUE)

SET @DATE = DATEADD(SECOND,30,@DATE)

END

INSERT INTO LAB02_LOG (DEVICEID,DATE_,VALUE_)
VALUES (1,'2022-08-027 07:30:00',18.9)

