

--Elimizde araç modellerinin olduðu bir veriseti var. Bu veriseti için rastgele plaka generate eden T-SQL scriptini yazalým.


SELECT * FROM LAB03_CARMODELS WHERE BRAND = 'Audi'
SELECT * FROM LAB03_CITIES
SELECT * FROM LAB03_PLATES
SELECT * FROM LAB03_LETTERS

DECLARE @I AS INT = 0
WHILE @I < 1000
BEGIN


	DECLARE @PLATE AS VARCHAR(20)
	DECLARE @CARID AS INT = 1
	DECLARE @CITYID AS INT = 41
	DECLARE @LETTER1 AS VARCHAR(1) = 'A'
	DECLARE @LETTER2 AS VARCHAR(1) = 'B'
	DECLARE @NUMBER AS INT = 1499
	DECLARE @RANDID AS INT 

	SET @CARID = 1 + (RAND() * 6538)
	SET @CITYID = 1 + (RAND() * 80)
	SET @RANDID = 1 + (RAND()*21)
	SELECT @LETTER1 = LETTER FROM LAB03_LETTERS WHERE ID = @RANDID

	SET @PLATE = REPLICATE('0',2-LEN(@CITYID)) + CONVERT(varchar,@CITYID)
	SET @PLATE = @PLATE + @LETTER1 + @LETTER2
	SET @PLATE = @PLATE + REPLICATE('0',4-LEN(@NUMBER)) + CONVERT(varchar,@NUMBER)
	INSERT INTO LAB03_PLATES(PLATE,CARID) VALUES (@PLATE,@CARID)
SET @I = @I + 1
END
	SELECT P.PLATE,C.* FROM LAB03_PLATES P
	JOIN LAB03_CARMODELS C ON C.ID = P.ID




SELECT @PLATE
