


CREATE FUNCTION DBO.GETMINPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @RESULT AS FLOAT
SELECT @RESULT = MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = @ITEMID
RETURN @RESULT

END


CREATE FUNCTION DBO.GETMAXPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @RESULT AS FLOAT
SELECT @RESULT = MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = @ITEMID
RETURN @RESULT

END


CREATE FUNCTION DBO.GETAVGPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @RESULT AS FLOAT
SELECT @RESULT = AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = @ITEMID
RETURN @RESULT

END