

CREATE FUNCTION DBO.GETMONTHNAME(@DATE AS DATETIME)
RETURNS VARCHAR(20)
AS
BEGIN
DECLARE @RESULT AS VARCHAR(20)
IF MONTH(@DATE) =1 SET @RESULT = '01.OCAK'
IF MONTH(@DATE) =1 SET @RESULT = '02.ÞUBAT'
IF MONTH(@DATE) =1 SET @RESULT = '03.MART'
IF MONTH(@DATE) =1 SET @RESULT = '04.NÝSAN'
IF MONTH(@DATE) =1 SET @RESULT = '05.MAYIS'
IF MONTH(@DATE) =1 SET @RESULT = '06.HAZÝRAN'
IF MONTH(@DATE) =1 SET @RESULT = '07.TEMMUZ'
IF MONTH(@DATE) =1 SET @RESULT = '08.AÐUSTOS'
IF MONTH(@DATE) =1 SET @RESULT = '09.EYLÜL'
IF MONTH(@DATE) =1 SET @RESULT = '10.EKÝM'
IF MONTH(@DATE) =1 SET @RESULT = '11.KASIM'
IF MONTH(@DATE) =1 SET @RESULT = '12.ARALIK'

RETURN @RESULT

END


SELECT DBO.GETMONTHNAME('2022-05-02')