
SELECT * FROM LAB07	


-- AKILLI KOD EKLEME SURECI

SELECT TOP(5) * FROM LAB07

SELECT TOP 10 CATEGORY1CODE + REPLICATE('0',6-LEN(ITEMCODE)) + ITEMCODE FROM LAB07


--REPLICATE Sutünü deðer eklemek için yapýlan koddur.


UPDATE LAB07 SET ITEMCODE =  CATEGORY1CODE + REPLICATE('0',6-LEN(ITEMCODE)) + ITEMCODE