
DECLARE @NUM1 AS INTEGER 
SET @NUM1 = 100
DECLARE @NUM2 AS INTEGER
SET @NUM2 = 250

DECLARE @TOPLAM AS INTEGER
DECLARE @CARPIM AS INTEGER
DECLARE @CIKAR AS INTEGER
DECLARE @BOLME AS FLOAT

SET @TOPLAM = @NUM1 + @NUM2
SET @CARPIM = @NUM1 * @NUM2
SET @CIKAR =  @NUM2 - @NUM1
SET @BOLME = CONVERT(FLOAT,@NUM2 / @NUM1)

SELECT @TOPLAM,@CARPIM,@CIKAR,@BOLME

 