

--Elimizde ürünlerin bulunduðu bir tablo, müþterilerin bulunduðu bir tablo ve satýþlarýn bulunduðu bir baþka tablo var.
--Burada rastgele bir müþteriye, rastgele bir üründen '2021-01-01-2021-12-31' tarihleri arasýnda rastgele bir tarihte,
--1-20 arasýnda rastgele miktarda ürün satýþý gerçekleþecek scripti yazýnýz.


SELECT * FROM LAB03_CUSTOMERS

SELECT * FROM LAB03_ITEMS

SELECT * FROM LAB03_SALES

DECLARE @CUSTOMERID AS INT
DECLARE @RANDID AS INT
DECLARE @UNITPRICE AS FLOAT 
DECLARE @ITEMID AS INT
SELECT @RANDID = 1 + (RAND()*9999)
SELECT @RANDID

SELECT @CUSTOMERID = ID FROM LAB03_CUSTOMERS WHERE ID = @RANDID

SELECT TOP 1 @CUSTOMERID = ID FROM LAB03_CUSTOMERS ORDER BY NEWID()

SELECT TOP 1 @CUSTOMERID = ID FROM LAB03_ITEMS ORDER BY NEWID()

SELECT TOP 1 @ITEMID = ID,@UNITPRICE = UNITPRICE FROM LAB03_ITEMS ORDER BY NEWID() 



DECLARE @DATE AS DATETIME
DECLARE @RAND AS INT
DECLARE @AMOUNT AS INT
DECLARE @LINETOTAL AS FLOAT

SET @LINETOTAL = @AMOUNT * @UNITPRICE
SET @AMOUNT = 1 + (RAND() * 19)
SET @RAND = RAND() *365
SET @DATE = DATEADD(DAY,@RAND,'2021-01-01')
SET @DATE = DATEADD(HOUR,8,@DATE)
SET @RAND = RAND()*12*60*60
SET @DATE = DATEADD(SECOND,@RAND,@DATE)
SELECT @RAND,@DATE,@AMOUNT,@LINETOTAL

INSERT INTO LAB03_SALES (CUSTOMERID,DATE_,AMOUNT,UNITPRICE,LINETOTAL)
VALUES (@CUSTOMERID,@ITEMID,@DATE,@AMOUNT,@UNITPRICE,@LINETOTAL)

SELECT * FROM LAB03_SALES