

DECLARE @CITY AS VARCHAR(150)
SET @CITY = 'Ý%'

DECLARE @BEGDATE AS DATE = '2019-03-01'
DECLARE @ANDDATE AS DATE = '2019-04-01'
DECLARE @BRAND AS VARCHAR(100) = 'ULKER'
DECLARE @TOTALPRICE AS FLOAT

SELECT @TOTALPRICE = SUM(TOTALPRICE) FROM SALES WHERE CITY LIKE @CITY AND DATE_ BETWEEN @BEGDATE AND @ANDDATE AND BRAND LIKE @BRAND

SELECT @TOTALPRICE