

--Tanýmlý olan bir deðiþkene SQL cümlesinden gelen veriyi atama.


DECLARE @TOTALSALE AS FLOAT
DECLARE @TOTALAMOUNT AS INT
DECLARE @ROWCOUNT AS INT 

--SET @TOTALSALE = (SELECT SUM(TOTALPRICE) FROM SALES WHERE CITY = 'ÝSTANBUL')
SET @TOTALAMOUNT = (SELECT SUM(AMOUNT) FROM SALES WHERE CITY = 'ÝSTANBUL')

SELECT @TOTALSALE = SUM(TOTALPRICE), @TOTALAMOUNT = SUM(AMOUNT),
@ROWCOUNT = COUNT(*)
FROM SALES WHERE CITY = 'ÝSTANBUL'

SELECT @TOTALSALE AS TOTALSALES,@TOTALAMOUNT AS TOTALAMOUNT,@ROWCOUNT AS TOTALROWCOUNT
