

--Elimizde bir satýþlar tablosu var, bir de müþteriler tablosu var. Bu tablodan rastgele seçilen 10 müþteriye bu zamana kadar yapmýþ olduðu alýþveriþin %50'si kadar
--hediye çeki verme kampanyasý yapýlmasý planlanýyor. Bir script ile 10 müþteri ve bu 10 müþteriye verilecek hediye çeklerini hesaplayan t-sql scriptini yazýnýz.

SELECT * FROM LAB04_CUSTOMERS


DECLARE @CUSTOMERID AS INT
SELECT TOP 1  @CUSTOMERID = ID FROM LAB04_CUSTOMERS
WHERE ID NOT IN(SELECT CUSTOMERID FROM RAFFLE )ORDER BY NEWID()

DECLARE @CUSTOMERNAME AS VARCHAR(100)
DECLARE @TOTALSALE AS FLOAT
DECLARE @GIFTPERCENT AS FLOAT = 50
DECLARE @GIFTTOTAL AS FLOAT 

SELECT 
@CUSTOMERNAME = C.CUSTOMERNAME,
@TOTALSALE = SUM(TOTALPRICE),@GIFTTOTAL= SUM(TOTALPRICE)*@GIFTPERCENT / 100 
FROM LAB04_SALES S
JOIN LAB04_CUSTOMERS C ON C.ID = S.CUSTOMERID
WHERE CUSTOMERID = @CUSTOMERID 
GROUP BY C.ID,C.CUSTOMERNAME

SELECT * FROM RAFFLE 


INSERT INTO RAFFLE (CUSTOMERID,CUSTOMERNAME,TOTALSALE,GIFTPERCENT,GIFTTOTAL)
VALUES (@CUSTOMERID,@CUSTOMERNAME,@TOTALSALE,@GIFTPERCENT,@GIFTTOTAL)

CREATE TABLE RAFFLE(ID INT IDENTITY(1,1),CUSTOMERID INT, CUSTOMERNAME VARCHAR(100),TOTALSALE FLOAT,GIFTPERCENT FLOAT,GIFTTOTAL FLOAT)