

--Cast/Convert Fonksiyonlarý

SELECT CAST('2022-06-25' AS DATE) AS DATE_

SELECT CAST('2023-04-12' AS DATETIME) AS DATETIMES

SELECT CONVERT(DATE,'2022-06-25') AS DATE_


SELECT CONVERT(BINARY,'MERHABA')

SELECT CONVERT(FLOAT,72)

SELECT CONVERT(INT,75.23)


SELECT GETDATE()

SELECT 'BUGÜNÜN TARÝHÝ : ' + CONVERT(VARCHAR,CONVERT(DATE,GETDATE()))
SELECT CONVERT(VARCHAR,CONVERT(DATE,GETDATE()))


SELECT CONVERT(VARCHAR,GETDATE(),101) 

