


SELECT * FROM LAB09 

ALTER TABLE LAB09 ADD BIRTHDATE2 DATE --TABLOYA ALAN EKLEME.


SELECT RIGHT('26.09.1998',4)

SELECT SUBSTRING('26.09.1998',4,2)

SELECT LEFT('26.09.1998',2)



UPDATE LAB09 SET BIRTHDATE2 = 
RIGHT(BIRTHDATE,4) + '-' + 
SUBSTRING(BIRTHDATE,4,2) + '-' +
LEFT(BIRTHDATE,2) 


UPDATE LAB09 SET BIRTHDATE2 = DATEFROMPARTS(RIGHT(BIRTHDATE,4),SUBSTRING(BIRTHDATE,4,2),LEFT(BIRTHDATE,2))
WHERE ISDATE(RIGHT(BIRTHDATE,4) + '-' + SUBSTRING(BIRTHDATE,4,2) + '-' +LEFT(BIRTHDATE,2)) = 1 --Bütün Tarih Kayýtlarýný günceller.