


SET LANGUAGE Turkish --Sistem dilini istediðimiz dile ayarlama da kullanýlýr.
SELECT YEAR(DATE_),
MONTH(DATE_),
DATENAME(MONTH,DATE_) MONTHNAME,
SUM(TOTALPRICE) TOTALPRICE FROM LAB04

WHERE DATEPART(DAY,DATE_) BETWEEN 10 AND 15
GROUP BY YEAR(DATE_), MONTH(DATE_),DATENAME(MONTH,DATE_)
ORDER BY 1