


SELECT 
CASE
WHEN AGE < 35 THEN 'GENÇ'
WHEN AGE BETWEEN 36 AND 55 THEN 'OLGUN'
WHEN AGE > 55 THEN 'YAÞLI'
END AS AGEGROUP,* FROM CUSTOMERS


SELECT * FROM CUSTOMERS 


SELECT 
CASE
WHEN GENDER = 'E' THEN 'ERKEK'
WHEN GENDER = 'K' THEN 'KADIN'
END AS GENDEREXP,* FROM CUSTOMERS


SELECT
CASE
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) <= 35 THEN 'GENÇ'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 55 THEN 'OLGUN'
WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) > 55 THEN 'YAÞLI'
END AS AGEGROUP,
DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,
* FROM CUSTOMERS