

SELECT IIF(CUSTOMERGENDER = 'E','ERKEK','KADIN') GENDEREXP,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES.dbo.SALES
GROUP BY CUSTOMERGENDER 

--IIF Komutu CASE/WHEN gibidir. IIF'de sadece 2 þart belirtilebilir.

SELECT IIF(GENDER = 'E','ERKEK','K') AS GENDEREXP,* FROM CUSTOMERS