


--Elimizde bir satýþ verisi var.Bu veride her bir þehirde erkeklerin ve kadýnlarýn ne kadar alýþveriþ yaptýðýný ve birbirine oranýný bulunuz
-- ve toplam ciro rakamýndaki orana göre her bir þehir için kadýnlarýn ortalamanýn altýnda mý yoksa üstünde mi alýþ veriþ yaptýðýný hesaplayýnýz.


SELECT CUSTOMERGENDER,SUM(TOTALPRICE) FROM LAB03
GROUP BY CUSTOMERGENDER


DECLARE @FEMALESALE AS FLOAT
DECLARE @MALESALE AS FLOAT
DECLARE @RATIO AS FLOAT

SELECT @FEMALESALE = SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'K'
SELECT @MALESALE = SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'E'

SET @RATIO = @FEMALESALE / @MALESALE

SELECT @RATIO


SELECT DISTINCT CITY,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'K' AND CITY=S.CITY) FEMALESALE,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'E' AND CITY=S.CITY) MALESALE,

(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'K' AND CITY=S.CITY)  /
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'E' AND CITY=S.CITY)  RATIO,

CASE
WHEN (SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'K' AND CITY=S.CITY)  /
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'E' AND CITY=S.CITY) > @RATIO THEN 'ORTALAMADAN YÜKSEK'
ELSE 'ORTALAMADAN DÜÞÜK'
END AS STATUS_

FROM LAB03 S ORDER BY 1 


select *,FEMALESALE/MALESALE AS RATIO from 

CASE 
WHEN FEMALESALE / MALESALE > @RATIO THEN 'ORTALAMADAN YÜKSEK'
ELSE 'ORTALAMADAN DÜÞÜK'
END AS STATUS_
(
SELECT DISTINCT CITY,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'K' AND CITY=S.CITY) FEMALESALE,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER = 'E' AND CITY=S.CITY) MALESALE
from lab03 s
) t
order by 1